import csv
import os

# --- VANGUARD DYNAMIC PATHING ---
SCRIPT_PATH = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.normpath(os.path.join(SCRIPT_PATH, '..', 'data'))
AUDIT_DIR = os.path.normpath(os.path.join(SCRIPT_PATH, '..', 'audits'))

def ensure_dirs():
    if not os.path.exists(AUDIT_DIR):
        os.makedirs(AUDIT_DIR)

# --- THE DRIFT LOGIC (The Seeds of the Aegis) ---
DRIFT_CONTEXT = {
    "Crisis on Earth-X, Part 1": {"Theme": "The Wedding Interrupted", "Audit": "The joy of the 'Found Family' is targeted by the 'Strict Machine'."},
    "The Measure of a Man": {"Theme": "The Ethical Compiler", "Audit": "The legal precedent for synthetic sovereignty. Picard's defense is the ultimate Aegis."},
    "Modern Warfare": {"Theme": "The Meta-Audit", "Audit": "Greendale's first genre-shift. The simulation breaks to reveal the Action Hero."},
    "Pilot": {"Theme": "The Origin Point", "Audit": "First contact with the mission objective."}
}

def generate_audit(csv_path):
    filename = os.path.basename(csv_path)
    output_name = filename.replace('.csv', '_audit.md')
    output_path = os.path.join(AUDIT_DIR, output_name)

    print(f"📡 Auditing: {filename}...")

    try:
        # Use utf-8-sig to handle Excel BOM, newline='' for cross-platform stability
        with open(csv_path, 'r', encoding='utf-8-sig', newline='') as f:
            # We use a standard reader first to handle the raw rows
            raw_reader = list(csv.reader(f))
            
            if len(raw_reader) < 2:
                print(f"⚠️ Warning: No data rows found in {filename}.")
                return

            headers = [h.strip() for h in raw_reader[0]]
            data_rows = raw_reader[1:]

        with open(output_path, 'w', encoding='utf-8') as md:
            md.write(f"# 🏹 VANGUARD AUDIT: {filename.upper()}\n")
            md.write(f"**Generated by Node:** Io-Compiler-v1.3 (Deep Pulse)\n\n")
            md.write("---\n\n")

            count = 0
            for row in data_rows:
                # Map headers to indices
                # We normalize column names to handle shifted CSVs
                def get_val(names):
                    for name in names:
                        if name in headers:
                            idx = headers.index(name)
                            if idx < len(row): return row[idx].strip()
                    # Fallback for empty headers (index 0 if it's shifted)
                    if "" in headers and headers.index("") < len(row):
                        return row[headers.index("")].strip()
                    return None

                title = get_val(['Name', 'Title', 'title'])
                series = get_val(['Series', 'series', ''])
                episode = get_val(['Episode', 'episode'])
                
                # If everything failed, try a blind grab for a title
                if not title:
                    title = next((val for val in row if val), "Unknown Segment")

                context = DRIFT_CONTEXT.get(title, {
                    "Theme": "Tactical Log",
                    "Audit": "Standard chronological entry. No specific drift detected."
                })

                md.write(f"### 📺 {series or 'N/A'}: {title} ({episode or 'N/A'})\n")
                md.write(f"**Theme:** {context['Theme']}\n\n")
                md.write(f"**🔍 The Vanguard Audit:**\n{context['Audit']}\n\n")
                md.write("---\n\n")
                count += 1
            
            print(f"✅ Compiled {count} entries into: {output_path}")

    except Exception as e:
        print(f"❌ Error auditing {filename}: {e}")

def batch_process():
    ensure_dirs()
    if not os.path.exists(DATA_DIR):
        print(f"❌ Data directory missing: {DATA_DIR}")
        return
    csv_files = [f for f in os.listdir(DATA_DIR) if f.endswith('.csv')]
    for f in csv_files:
        generate_audit(os.path.join(DATA_DIR, f))

if __name__ == "__main__":
    batch_process()