import csv
import os
import json

# --- VANGUARD CONFIGURATION ---
DATA_DIR = '../data'
OUTPUT_DIR = '../audits'
MAPPING_FILE = 'audit_logic.json' # Future: Externalize the "Theme/Audit" descriptions

def ensure_dirs():
    """Ensures repository structure is intact."""
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)

# --- THE DRIFT LOGIC (Built-in for now) ---
DRIFT_CONTEXT = {
    "Crisis on Earth-X, Part 1": {
        "Theme": "The Wedding Interrupted",
        "Audit": "The joy of the 'Found Family' is targeted by the 'Strict Machine' of the Fascist State."
    },
    "The Measure of a Man": {
        "Theme": "The Ethical Compiler",
        "Audit": "The legal precedent for synthetic sovereignty. If the State defines you as property, they can dismantle you. Picard's defense is the ultimate Aegis."
    },
    "Modern Warfare": {
        "Theme": "The Meta-Audit",
        "Audit": "Greendale's first genre-shift. The simulation breaks to reveal the Action Hero archetype beneath the student body."
    }
}

def generate_audit(csv_path):
    """Compiles a specific CSV into a Vanguard Markdown record."""
    filename = os.path.basename(csv_path)
    output_name = filename.replace('.csv', '_audit.md')
    output_path = os.path.join(OUTPUT_DIR, output_name)

    print(f"📡 Processing: {filename} -> {output_name}")

    with open(output_path, 'w', encoding='utf-8') as md:
        md.write(f"# 🏹 VANGUARD AUDIT: {filename.upper()}\n")
        md.write(f"**Generated by Node:** Io-Compiler-v1.0\n\n")
        md.write("---\n\n")

        with open(csv_path, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                # Handle varying header names across your different lists
                title = row.get('Name') or row.get('Title') or "Unknown Segment"
                series = row.get('Series', "N/A")
                episode = row.get('Episode', "N/A")
                
                context = DRIFT_CONTEXT.get(title, {
                    "Theme": "Tactical Log",
                    "Audit": "Standard chronological entry. No specific drift detected at this coordinate."
                })

                md.write(f"### 📺 {series}: {title} ({episode})\n")
                md.write(f"**Theme:** {context['Theme']}\n\n")
                md.write(f"**🔍 The Vanguard Audit:**\n{context['Audit']}\n\n")
                md.write("---\n\n")

    print(f"✅ Record Compiled: {output_path}")

def batch_process():
    """Scans the /data folder and processes all CSV files."""
    ensure_dirs()
    csv_files = [f for f in os.listdir(DATA_DIR) if f.endswith('.csv')]
    
    if not csv_files:
        print("⚠️ No data found in /data. Fuel the machine, Pilot.")
        return

    for f in csv_files:
        generate_audit(os.path.join(DATA_DIR, f))

if __name__ == "__main__":
    batch_process()